# Generated by Django 5.0.1 on 2025-09-02 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('install_args', models.CharField(blank=True, help_text='Parâmetros de linha de comando adicionais para o instalador (ex: /S, /VERYSILENT, /qn, etc)', max_length=255, null=True, verbose_name='Parâmetros adicionais')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('version', models.CharField(max_length=50, verbose_name='Versão')),
                ('category', models.CharField(choices=[('OFFICE', 'Pacote Office'), ('BROWSER', 'Navegadores'), ('DEVELOPMENT', 'Desenvolvimento'), ('DESIGN', 'Design'), ('SECURITY', 'Segurança'), ('UTILITIES', 'Utilitários'), ('OTHER', 'Outros')], default='OTHER', max_length=20, verbose_name='Categoria')),
                ('icon', models.ImageField(blank=True, help_text='Ícone do software (formato PNG ou JPG)', null=True, upload_to='software/icons/%Y/%m/%d/', verbose_name='Ícone')),
                ('installer', models.FileField(help_text='Arquivo executável ou pacote de instalação', upload_to='software/installers/%Y/%m/%d/', verbose_name='Arquivo de Instalação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('download_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Downloads')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('install_script', models.TextField(blank=True, help_text='Comandos para instalação (opcional)', verbose_name='Script de Instalação')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Softwares',
                'ordering': ['name'],
                'permissions': [('can_download_software', 'Pode baixar softwares'), ('can_manage_software', 'Pode gerenciar softwares')],
            },
        ),
        migrations.CreateModel(
            name='SoftwareRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('from_software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from_software', to='store.software', verbose_name='Software de Origem')),
                ('to_software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to_software', to='store.software', verbose_name='Software Relacionado')),
            ],
            options={
                'verbose_name': 'Relacionamento de Software',
                'verbose_name_plural': 'Relacionamentos de Software',
                'unique_together': {('from_software', 'to_software')},
            },
        ),
        migrations.AddField(
            model_name='software',
            name='related_software',
            field=models.ManyToManyField(blank=True, through='store.SoftwareRelationship', to='store.software', verbose_name='Softwares Relacionados'),
        ),
        migrations.CreateModel(
            name='SoftwareScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Tamanho recomendado: 800x600 pixels', upload_to='software/screenshots/', verbose_name='Imagem')),
                ('caption', models.CharField(blank=True, help_text='Descrição opcional da imagem', max_length=200, verbose_name='Legenda')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição das imagens', verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='store.software', verbose_name='Software')),
            ],
            options={
                'verbose_name': 'Screenshot',
                'verbose_name_plural': 'Screenshots',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nome do Software')),
                ('description', models.TextField(blank=True, verbose_name='Descrição / Justificativa')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoria sugerida')),
                ('reference_url', models.URLField(blank=True, verbose_name='Link de referência')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Sugestão de Software',
                'verbose_name_plural': 'Sugestões de Software',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=255, verbose_name='Hostname')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em progresso'), ('completed', 'Concluído'), ('error', 'Erro')], default='pending', max_length=20, verbose_name='Status')),
                ('installer_url', models.URLField(help_text='URL para download do instalador', max_length=500, verbose_name='URL do Instalador')),
                ('log', models.TextField(blank=True, help_text='Log da instalação', verbose_name='Log')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_tasks', to='store.software', verbose_name='Software')),
            ],
            options={
                'verbose_name': 'Tarefa de Instalação',
                'verbose_name_plural': 'Tarefas de Instalação',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hostname', 'status'], name='store_insta_hostnam_9b895c_idx'), models.Index(fields=['created_at'], name='store_insta_created_571c1b_idx'), models.Index(fields=['updated_at'], name='store_insta_updated_620b57_idx')],
            },
        ),
        migrations.CreateModel(
            name='SoftwareDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do download')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, help_text='Informações do navegador do usuário', verbose_name='User Agent')),
                ('version', models.CharField(blank=True, help_text='Versão do software no momento do download', max_length=50, verbose_name='Versão')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='store.software', verbose_name='Software')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Download de Software',
                'verbose_name_plural': 'Downloads de Software',
                'ordering': ['-downloaded_at'],
                'indexes': [models.Index(fields=['software', 'downloaded_at'], name='store_softw_softwar_5e11d0_idx'), models.Index(fields=['user', 'downloaded_at'], name='store_softw_user_id_931e57_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='software',
            index=models.Index(fields=['name'], name='store_softw_name_4b0d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='software',
            index=models.Index(fields=['category'], name='store_softw_categor_fd6c73_idx'),
        ),
        migrations.AddIndex(
            model_name='software',
            index=models.Index(fields=['is_active'], name='store_softw_is_acti_6d3c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='software',
            index=models.Index(fields=['is_featured'], name='store_softw_is_feat_c203ce_idx'),
        ),
        migrations.AddIndex(
            model_name='software',
            index=models.Index(fields=['created_at'], name='store_softw_created_bd5f85_idx'),
        ),
        migrations.AddIndex(
            model_name='softwaresuggestion',
            index=models.Index(fields=['status'], name='store_softw_status_489a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='softwaresuggestion',
            index=models.Index(fields=['created_at'], name='store_softw_created_d5eeae_idx'),
        ),
    ]
