version: "3.9"

services:
  web:
    build: .
    container_name: software_store_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - media_data:/app/media
      - staticfiles_data:/app/staticfiles
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  media_data:
  staticfiles_data:
